BUSCACURSOS_TABLE_NUMBER = 5
BUSCACURSOS_RESULT_CLASSES = ["resultadosRowPar", "resultadosRowImpar"]

BUSCACURSOS_NRC = "NRC"
BUSCACURSOS_SIGLA = "Sigla"
BUSCACURSOS_NOMBRE = "Nombre"
BUSCACURSOS_PROFESOR = "Profesor"
BUSCACURSOS_RETIRO = "Permite Retiro"
BUSCACURSOS_INGLES = "¿Se dicta en inglés?"
BUSCACURSOS_SECCION = "Sec."
BUSCACURSOS_CATEGORIA = "Categoría"
BUSCACURSOS_CAMPUS = "Campus"
BUSCACURSOS_CREDITOS = "Créd."
BUSCACURSOS_APROB_ESPECIAL = "¿Requiere Aprob. Especial?"
BUSCACURSOS_HORARIO = "Horario"
BUSCACURSOS_SI_RETIRO = "SI"
BUSCACURSOS_UNIDAD_COLSPAN = 16
